# Site settings
title: Graham Beer Blog
description: "System Engineer, PowerShell, Puppet, Docker and SCCM who is a huge automation fan!"
url: 'https://graham-beer.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Graham Beer'
  email: Graham.Beer@DTLK.co.uk
  # twitter_username: 
  # facebook_username: 
  github_username:  Graham-Beer
  linkedin_username: https://uk.linkedin.com/in/graham-beer-7a178951

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

  syntax_highlighter_opts:    
    css_class: 'highlight'    
    span:      
      line_numbers: false    
    block:      
      line_numbers: true      
      start_line: 1

gems: ['jekyll-paginate', 'jemoji', 'jekyll-sitemap', 'jekyll-gist']

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
