# Site settings
title: ${Graham Beer} = blog
description: "System Engineer, PowerShell Developer, WinOps and a huge automation fan! 
  <!--
      PeoplePerHour Profile Widget
      The div#pph-hire me is the element
      where the iframe will be inserted.
      You may move this element wherever
      you need to display the widget
  -->
  <div id="pph-hireme"></div>
  <script type="text/javascript">
  (function(d, s) {
      var useSSL = 'https:' == document.location.protocol;
      var js, where = d.getElementsByTagName(s)[0],
      js = d.createElement(s);
      js.src = (useSSL ? 'https:' : 'http:') +  '//www.peopleperhour.com/hire/1643589316/1938983.js?width=300&height=135&orientation=vertical&theme=dark&rnd='+parseInt(Math.random()*10000, 10);
      try { where.parentNode.insertBefore(js, where); } catch (e) { if (typeof console !== 'undefined' && console.log && e.stack) { console.log(e.stack); } }
  }(document, 'script'));
  </script>"
url: 'https://graham-beer.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Graham Beer'
  email: Graham.Beer@DTLK.co.uk
  # twitter_username: 
  # facebook_username: 
  github_username: Graham-Beer
  linkedin_username: graham-beer-7a178951
  resume: PDF/CV_Graham_Beer.pdf

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

  syntax_highlighter_opts:    
    css_class: 'highlight'    
    span:      
      line_numbers: false    
    block:      
      line_numbers: true      
      start_line: 1

gems: ['jekyll-paginate', 'jemoji', 'jekyll-sitemap', 'jekyll-gist']

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
