# Site settings
# title: ${Graham Beer} = 'blog'
title: name := "Graham Beer"
description: '`Cloud Engineer with his head in the AWS clouds,
authored chapters in the PowerShell Conference Book 1 & 2 
and currently learning and enjoying Go'
url: 'https://graham-beer.github.io'
baseurl: '/'
google_analytics: 'UA-159639316-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Graham Beer'
  email: Graham.Beer@outlook.com
  twitter_username: GKBeer
  # facebook_username: 
  github_username: Graham-Beer
  linkedin_username: graham-beer-7a178951
  resume: PDF/CV_Graham_Beer.pdf

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

plugins:
  - jekyll-time-to-read

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

  syntax_highlighter_opts:    
    css_class: 'highlight'    
    span:      
      line_numbers: false    
    block:      
      line_numbers: true      
      start_line: 1

gems: ['jekyll-paginate', 'jemoji', 'jekyll-sitemap', 'jekyll-gist']

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
